# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: OpenMDW-1.1
"""Re-render an already-published page: the page IS its own input.

For a finished run whose upstream numbers are gone (`v1a_dedup_probe`), there is no
data snapshot to rebuild from — but the published HTML still carries every card. This
module parses those cards back out and re-renders them through `html.page()`, so a
frozen run is still generated by this repo: it picks up nav and design-system changes,
and nothing in it depends on the pipeline that originally produced it.

The card bodies round-trip as `{"raw": ...}` sections — kept verbatim, never reflowed.
So the content is *preserved*, not *recomputed*: editing a number here means editing
markup. Re-rendering an unchanged page is a fixpoint (byte-identical), which is what
`build.py --check` asserts.
"""
from __future__ import annotations

import argparse
import html as _html
import re
from pathlib import Path

from . import html as report_html
from .nav import RUNS, SITE_NAME

_CARD_OPEN = '<div class="card">'


def _split_cards(main_html: str) -> list[str]:
    """Split `<main>`'s inner HTML into top-level `<div class="card">…</div>` blocks,
    returning each card's inner HTML. Depth-aware: cards nest plenty of divs."""
    cards: list[str] = []
    pos = 0
    while (start := main_html.find(_CARD_OPEN, pos)) != -1:
        depth, i = 1, start + len(_CARD_OPEN)
        body_start = i
        while depth and (m := re.compile(r"<(/?)div\b[^>]*>").search(main_html, i)):
            depth += -1 if m.group(1) else 1
            i = m.end()
        if depth:
            raise ValueError("unbalanced <div> inside a card")
        cards.append(main_html[body_start:i - len("</div>")])
        pos = i
    return cards


def parse_page(page_html: str) -> tuple[str, list[dict]]:
    """`(title, sections)` for an already-rendered page. The heading of each card
    becomes an `{"h"}` section (so `html.page()` re-escapes it identically) and the
    rest of the card becomes one verbatim `{"raw"}` section."""
    title = _html.unescape(re.search(r"<title>(.*?)</title>", page_html, re.S).group(1))
    main = re.search(r'<main class="container">(.*)</main>', page_html, re.S).group(1)

    sections: list[dict] = []
    for card in _split_cards(main):
        heading = re.match(r"<h2>(.*?)</h2>", card, re.S)
        if heading:
            sections.append({"h": _html.unescape(heading.group(1))})
            card = card[heading.end():]
        if card:
            sections.append({"raw": card})
    return title, sections


def build_page(source: Path, out_dir: Path, nav: list[tuple[str, str]], current: str) -> Path:
    """Re-render `source` into `out_dir/<current>`. `source` is normally that same
    published page — the page is its own source of truth."""
    page_html = Path(source).read_text()
    title, sections = parse_page(page_html)

    rendered = report_html.page(title, sections, nav=nav, current=current, site_name=SITE_NAME)
    # A page with no figures ships without the plotly CDN <script>; don't add one back.
    plotly_tag = f'<script src="{report_html.PLOTLY_CDN}"></script>'
    if plotly_tag not in page_html:
        rendered = rendered.replace(plotly_tag, "", 1)

    out = Path(out_dir) / current
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered)
    return out


def build_run(run: str, site_root: Path, out_dir: Path | None = None) -> list[Path]:
    """Re-render every page of a frozen run. Reads from `site_root/run`, writes to
    `out_dir` (defaults to reading and writing the same directory, in place)."""
    src_dir = Path(site_root) / run
    dst_dir = Path(out_dir) if out_dir is not None else src_dir
    nav = RUNS[run]
    return [build_page(src_dir / href, dst_dir, nav, href) for href, _ in nav]


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="v1a_dedup_probe", choices=sorted(RUNS))
    ap.add_argument("--site-root", type=Path, default=Path("umi400h"))
    ap.add_argument("--out-dir", type=Path, default=None)
    args = ap.parse_args(argv)

    for out in build_run(args.run, args.site_root, args.out_dir):
        print(f"[done] wrote {out}")


if __name__ == "__main__":
    main()
